CREATE TABLE my_table (id INT PRIMARY KEY, name VARCHAR(255), age INT, city VARCHAR(255));
INSERT INTO my_table (id, name, age, city) VALUES (4113, 'Heidi', 26, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8010, 'David', 25, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6794, 'Heidi', 55, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1921, 'Ivan', 45, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5827, 'Alice', 63, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (2463, 'Alice', 41, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2902, 'Alice', 41, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (353, 'Grace', 29, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2976, 'Judy', 31, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5439, 'Alice', 44, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5891, 'David', 32, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4343, 'Frank', 50, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7350, 'Alice', 62, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4268, 'Heidi', 30, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8079, 'Grace', 35, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4605, 'Eve', 61, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7484, 'Alice', 18, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2569, 'Alice', 20, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (69, 'Ivan', 44, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2215, 'Heidi', 56, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5127, 'Heidi', 64, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5309, 'Frank', 38, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5017, 'Alice', 54, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (66, 'Frank', 28, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9656, 'Bob', 62, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4458, 'Ivan', 46, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5044, 'Charlie', 22, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8559, 'Judy', 42, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9559, 'Grace', 50, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5659, 'Judy', 56, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2328, 'Alice', 43, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7937, 'Bob', 18, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4871, 'Bob', 21, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5140, 'Judy', 38, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1419, 'Alice', 60, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5747, 'Alice', 61, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8904, 'Grace', 65, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (882, 'Grace', 24, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5547, 'Eve', 37, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3124, 'Ivan', 61, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (2446, 'Ivan', 20, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8248, 'Heidi', 57, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6598, 'Heidi', 20, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9070, 'Eve', 61, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4085, 'David', 51, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9995, 'Charlie', 19, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6659, 'Judy', 26, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9803, 'Eve', 53, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2835, 'Ivan', 46, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3048, 'Bob', 65, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9313, 'Alice', 32, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9012, 'Frank', 40, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8085, 'Charlie', 59, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4857, 'Charlie', 37, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5258, 'Ivan', 28, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7976, 'Eve', 25, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (674, 'Bob', 33, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (606, 'Grace', 56, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7020, 'Eve', 48, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5831, 'David', 20, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4197, 'Grace', 35, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3201, 'Bob', 64, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7833, 'Heidi', 27, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7556, 'Grace', 28, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3282, 'Charlie', 45, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (302, 'Ivan', 64, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8896, 'David', 59, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7686, 'Frank', 34, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8602, 'Heidi', 37, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9046, 'Judy', 25, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (98, 'Ivan', 59, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (2878, 'Ivan', 54, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6076, 'Grace', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3382, 'Ivan', 21, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (967, 'David', 47, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6094, 'Alice', 45, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2425, 'Bob', 44, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3706, 'Judy', 22, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4169, 'Charlie', 25, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (3348, 'Eve', 34, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7054, 'Alice', 22, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (617, 'Frank', 27, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2726, 'Judy', 18, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9580, 'Judy', 53, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5155, 'Ivan', 24, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6792, 'Judy', 62, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3756, 'David', 28, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1354, 'Heidi', 58, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5650, 'David', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5082, 'Judy', 21, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1508, 'David', 47, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (278, 'Charlie', 26, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3287, 'Grace', 50, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9037, 'David', 18, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6643, 'Alice', 49, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1425, 'Eve', 53, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9045, 'Alice', 30, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8722, 'Grace', 41, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4969, 'David', 57, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (825, 'Heidi', 53, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8517, 'Grace', 54, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (192, 'Judy', 58, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (214, 'Eve', 58, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8636, 'Judy', 40, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1537, 'Grace', 33, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5847, 'Heidi', 59, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (961, 'Heidi', 61, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (70, 'Grace', 61, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9797, 'Heidi', 44, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8926, 'Frank', 32, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6922, 'Ivan', 53, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9617, 'Frank', 20, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (323, 'Judy', 38, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (3694, 'Grace', 40, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1660, 'Heidi', 39, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9249, 'Eve', 57, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1794, 'Frank', 57, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (3073, 'Eve', 52, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4365, 'Judy', 53, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (493, 'David', 44, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6332, 'Heidi', 60, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3574, 'Judy', 32, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3431, 'Frank', 53, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6795, 'Grace', 26, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5784, 'David', 45, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1203, 'Eve', 48, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6900, 'Heidi', 65, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9116, 'Judy', 33, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7958, 'Eve', 38, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (212, 'Frank', 48, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (877, 'Charlie', 44, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6598, 'Bob', 46, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2116, 'Charlie', 61, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8228, 'Charlie', 53, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8557, 'Bob', 41, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (924, 'Frank', 43, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2688, 'Heidi', 32, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3206, 'Grace', 20, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1350, 'Frank', 56, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6658, 'David', 27, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6093, 'Bob', 64, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8518, 'David', 51, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2996, 'Charlie', 24, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6073, 'Grace', 58, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3297, 'Judy', 49, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (477, 'Bob', 40, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1517, 'David', 20, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2338, 'Grace', 64, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7874, 'Bob', 37, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6131, 'David', 43, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6547, 'Ivan', 55, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8265, 'Eve', 30, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7321, 'Charlie', 24, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3239, 'Grace', 57, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3105, 'Grace', 65, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8373, 'Grace', 58, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (3798, 'Grace', 45, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9720, 'Heidi', 59, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1622, 'Alice', 19, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9075, 'Ivan', 27, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4094, 'Bob', 20, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7572, 'David', 44, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (4426, 'Bob', 34, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9920, 'Charlie', 35, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (55, 'Bob', 33, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7642, 'Charlie', 33, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3536, 'Eve', 26, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4853, 'David', 24, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (9283, 'Ivan', 41, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5177, 'Alice', 30, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4432, 'Frank', 61, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (635, 'Frank', 24, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8743, 'Grace', 25, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4207, 'Grace', 61, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8719, 'Bob', 51, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7639, 'Judy', 32, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1745, 'Alice', 33, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4506, 'Frank', 18, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8401, 'Eve', 62, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (61, 'David', 40, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (451, 'Alice', 26, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8716, 'Judy', 64, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1574, 'David', 48, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (3708, 'Ivan', 62, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (51, 'Bob', 37, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (714, 'Heidi', 36, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8962, 'Eve', 61, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9228, 'Ivan', 65, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7178, 'Judy', 26, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6891, 'Eve', 50, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (79, 'Eve', 19, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4535, 'Judy', 23, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7386, 'Eve', 52, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8, 'Charlie', 59, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1451, 'Alice', 47, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (9111, 'Charlie', 44, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (2581, 'Bob', 64, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (997, 'Ivan', 47, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (5096, 'Judy', 23, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9440, 'Bob', 21, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8761, 'Charlie', 23, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1465, 'David', 39, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7686, 'Ivan', 36, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7266, 'Eve', 25, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8626, 'Grace', 43, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6298, 'Charlie', 18, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6595, 'Ivan', 35, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1965, 'Grace', 24, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (10000, 'Bob', 45, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8699, 'Charlie', 44, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1339, 'Alice', 59, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3236, 'Frank', 48, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9662, 'Frank', 19, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6452, 'Charlie', 28, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (893, 'Bob', 65, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7271, 'Charlie', 22, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3371, 'Eve', 40, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (4769, 'Eve', 29, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9452, 'Judy', 49, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5849, 'Bob', 34, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3475, 'Ivan', 51, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9508, 'Judy', 55, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (647, 'Charlie', 21, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3064, 'Frank', 57, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2731, 'Charlie', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5531, 'Charlie', 53, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6230, 'Grace', 61, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3807, 'Charlie', 55, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8804, 'Frank', 34, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4508, 'Grace', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2412, 'Judy', 55, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6997, 'Grace', 52, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7811, 'Alice', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4999, 'Eve', 50, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2543, 'Charlie', 58, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7446, 'Alice', 44, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5117, 'Frank', 64, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6564, 'Heidi', 48, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6851, 'Alice', 65, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8995, 'Eve', 21, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8324, 'David', 18, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5487, 'Grace', 38, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2224, 'Ivan', 37, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8351, 'Frank', 18, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8646, 'Judy', 65, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2056, 'Heidi', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6691, 'Charlie', 39, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9002, 'Ivan', 32, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3437, 'Judy', 43, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4796, 'Judy', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4293, 'Ivan', 39, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2136, 'Eve', 32, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1271, 'Grace', 45, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1191, 'Alice', 45, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1185, 'Heidi', 62, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8528, 'Heidi', 34, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6037, 'Charlie', 45, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5001, 'Frank', 47, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7735, 'Judy', 59, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4670, 'Charlie', 62, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3607, 'Heidi', 18, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (360, 'David', 52, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9002, 'David', 36, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2711, 'Charlie', 34, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1738, 'David', 19, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7084, 'Bob', 52, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6768, 'Bob', 42, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8618, 'Charlie', 21, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4335, 'Bob', 18, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6904, 'Alice', 23, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6020, 'Heidi', 23, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5562, 'Eve', 50, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4493, 'Charlie', 49, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (663, 'Judy', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7501, 'Judy', 24, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6273, 'Eve', 51, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4332, 'Alice', 25, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (422, 'Charlie', 65, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (3462, 'Bob', 22, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8386, 'Heidi', 39, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1245, 'Heidi', 32, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4426, 'Frank', 22, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7686, 'Judy', 44, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (405, 'Heidi', 51, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9680, 'Ivan', 47, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9615, 'Judy', 28, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (77, 'Bob', 38, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6834, 'Bob', 65, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (4181, 'David', 62, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2641, 'Heidi', 19, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9087, 'Alice', 53, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2233, 'Ivan', 20, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8324, 'David', 34, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4109, 'Bob', 46, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7303, 'David', 27, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1295, 'Bob', 21, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6488, 'Charlie', 62, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5689, 'Grace', 21, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8664, 'Frank', 65, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1224, 'Frank', 29, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5577, 'Grace', 58, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2148, 'Frank', 48, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7842, 'Ivan', 21, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3228, 'Grace', 36, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8899, 'Eve', 27, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5160, 'Grace', 35, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (184, 'Frank', 59, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1231, 'Alice', 45, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (5899, 'Bob', 62, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7380, 'David', 19, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (849, 'Alice', 27, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8592, 'Alice', 53, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7367, 'Heidi', 32, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7066, 'Alice', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (831, 'Grace', 57, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1735, 'Bob', 54, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9793, 'Ivan', 39, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1874, 'Eve', 53, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3815, 'Ivan', 34, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7036, 'Grace', 51, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9304, 'Bob', 53, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4962, 'Charlie', 49, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5067, 'Alice', 60, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8238, 'Ivan', 50, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9673, 'Charlie', 58, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4000, 'David', 39, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8390, 'Eve', 52, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (305, 'Charlie', 27, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1042, 'Bob', 35, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2317, 'Judy', 56, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3427, 'Ivan', 46, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8706, 'Alice', 26, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2710, 'Ivan', 19, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7934, 'Eve', 61, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (4325, 'Bob', 31, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1800, 'Grace', 50, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9630, 'Eve', 52, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3186, 'Charlie', 18, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9328, 'Ivan', 46, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9857, 'Bob', 40, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9354, 'Ivan', 50, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7163, 'Alice', 37, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2378, 'Heidi', 45, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5133, 'Judy', 27, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2759, 'Heidi', 58, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5121, 'Ivan', 18, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8585, 'Judy', 35, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1462, 'Charlie', 43, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (704, 'Eve', 42, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7798, 'Charlie', 50, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7184, 'Charlie', 31, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6631, 'Frank', 26, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (251, 'Heidi', 26, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4131, 'Eve', 47, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2444, 'Eve', 27, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2061, 'Alice', 50, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (4027, 'Bob', 26, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (375, 'Ivan', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7366, 'Bob', 26, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2142, 'Bob', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2725, 'David', 45, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7296, 'Frank', 25, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4250, 'Bob', 59, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3715, 'Alice', 46, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4160, 'Bob', 45, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (310, 'David', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7706, 'David', 51, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6303, 'Judy', 22, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9726, 'Eve', 37, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (9903, 'Heidi', 62, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (64, 'Grace', 38, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8575, 'Alice', 39, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (5890, 'Eve', 58, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8773, 'Bob', 21, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5764, 'Alice', 23, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (9604, 'Grace', 19, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4556, 'Judy', 24, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7448, 'Alice', 62, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9036, 'Charlie', 28, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1667, 'Charlie', 21, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2549, 'David', 28, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7878, 'Judy', 28, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2799, 'Frank', 25, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7727, 'Bob', 45, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2942, 'Charlie', 35, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1813, 'Frank', 18, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3299, 'Frank', 51, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3486, 'Judy', 65, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1527, 'Bob', 55, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1358, 'Frank', 21, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3033, 'Ivan', 23, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (533, 'Alice', 54, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8041, 'David', 35, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (186, 'Charlie', 44, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7607, 'Alice', 35, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7048, 'Charlie', 47, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (278, 'Alice', 59, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5321, 'Bob', 25, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7338, 'Judy', 46, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6880, 'David', 45, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (186, 'Grace', 26, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3878, 'Ivan', 63, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7720, 'Eve', 55, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7975, 'Charlie', 48, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3034, 'Alice', 41, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2353, 'Frank', 30, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3982, 'Bob', 26, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9561, 'Grace', 58, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4365, 'Judy', 42, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3530, 'Grace', 26, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5016, 'David', 42, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (4599, 'David', 46, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9771, 'Eve', 21, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3805, 'Bob', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2675, 'Frank', 27, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6816, 'Grace', 33, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5847, 'Heidi', 28, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7279, 'Charlie', 30, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4557, 'Heidi', 28, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7973, 'Charlie', 52, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (109, 'Charlie', 48, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (494, 'Judy', 29, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2279, 'Charlie', 21, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (4146, 'David', 57, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (170, 'Ivan', 50, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6191, 'Bob', 19, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8140, 'Bob', 25, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2659, 'Frank', 59, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7170, 'Judy', 22, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7420, 'Judy', 45, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3621, 'Alice', 64, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (4802, 'Frank', 60, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5405, 'Grace', 59, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7870, 'Ivan', 57, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1035, 'Bob', 21, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2444, 'Alice', 56, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1538, 'David', 57, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (435, 'Eve', 38, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6948, 'Bob', 30, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1298, 'Grace', 20, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7344, 'Bob', 26, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (897, 'Frank', 28, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1479, 'Eve', 28, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3166, 'Grace', 42, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4816, 'David', 30, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3838, 'Judy', 30, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8495, 'Judy', 35, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1533, 'Bob', 47, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8408, 'Grace', 29, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2454, 'Eve', 20, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (201, 'Judy', 51, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6726, 'Frank', 63, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3579, 'Eve', 52, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9349, 'Bob', 22, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1067, 'David', 31, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3663, 'Charlie', 29, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6480, 'Frank', 45, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2240, 'Judy', 26, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4746, 'David', 26, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8984, 'Alice', 38, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7902, 'Ivan', 40, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9846, 'David', 56, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2612, 'Grace', 55, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7204, 'Eve', 28, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (431, 'David', 55, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7119, 'Ivan', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2557, 'Ivan', 34, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8218, 'Ivan', 24, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3988, 'Ivan', 42, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9984, 'Frank', 22, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1787, 'Ivan', 23, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8191, 'Eve', 48, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1928, 'Ivan', 52, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2845, 'Grace', 28, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3455, 'David', 45, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6647, 'Judy', 42, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1038, 'Charlie', 46, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4699, 'Grace', 56, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2659, 'Frank', 62, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7346, 'Alice', 60, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4235, 'Judy', 45, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8177, 'Eve', 51, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3104, 'David', 31, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6256, 'Grace', 31, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7231, 'Charlie', 18, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9313, 'Alice', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9772, 'Frank', 25, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4514, 'Frank', 38, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9911, 'Judy', 45, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5105, 'Ivan', 38, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6857, 'Eve', 60, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (4912, 'Bob', 62, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2231, 'Eve', 45, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8848, 'Grace', 32, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7964, 'Heidi', 52, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3388, 'Bob', 38, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4235, 'Eve', 38, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (61, 'Bob', 36, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4929, 'Alice', 47, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7730, 'Grace', 49, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7916, 'Grace', 36, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2441, 'Grace', 34, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (400, 'Grace', 47, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7876, 'Bob', 19, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7874, 'Eve', 33, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4673, 'Alice', 42, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4515, 'Heidi', 20, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (940, 'Alice', 43, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8135, 'Frank', 63, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6361, 'Grace', 49, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (714, 'Charlie', 61, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5644, 'Judy', 46, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1693, 'Charlie', 44, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4186, 'Bob', 32, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3339, 'Eve', 54, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (77, 'Grace', 49, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5847, 'Alice', 37, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (4421, 'Charlie', 24, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5823, 'Eve', 28, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (833, 'Frank', 50, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (891, 'Ivan', 45, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7893, 'Ivan', 24, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6235, 'Alice', 40, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1005, 'David', 32, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6213, 'Grace', 60, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4565, 'David', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (3506, 'Bob', 18, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1649, 'Heidi', 21, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7038, 'David', 40, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9718, 'Grace', 49, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6992, 'Alice', 65, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1988, 'Grace', 55, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (788, 'Frank', 64, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6015, 'Ivan', 47, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1708, 'Bob', 18, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9138, 'Frank', 49, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4401, 'Eve', 28, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6799, 'Bob', 37, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (107, 'Ivan', 30, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4229, 'Judy', 45, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2062, 'Alice', 40, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4446, 'Alice', 65, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8530, 'Charlie', 53, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1968, 'Bob', 57, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6352, 'Judy', 31, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5460, 'Charlie', 39, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3139, 'Eve', 50, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5162, 'Bob', 37, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6714, 'Charlie', 43, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6425, 'Grace', 31, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8164, 'Heidi', 39, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7513, 'Alice', 35, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3985, 'Alice', 30, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1335, 'Heidi', 56, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4988, 'David', 33, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3282, 'David', 27, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7654, 'Bob', 26, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7606, 'Charlie', 51, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2611, 'Heidi', 48, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8060, 'Charlie', 18, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5902, 'Heidi', 53, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6007, 'David', 21, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (591, 'David', 54, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1112, 'Ivan', 32, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5558, 'Bob', 30, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (953, 'Charlie', 29, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (970, 'Charlie', 21, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7448, 'Ivan', 29, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4685, 'Alice', 45, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9642, 'Charlie', 40, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2423, 'David', 33, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8257, 'Charlie', 25, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1405, 'Ivan', 28, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7818, 'Grace', 23, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2054, 'Bob', 48, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8341, 'Alice', 55, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8499, 'Heidi', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7664, 'Alice', 22, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (1470, 'Alice', 38, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1501, 'Judy', 28, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1934, 'Charlie', 20, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (1379, 'Judy', 47, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3782, 'Judy', 38, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9700, 'Grace', 40, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1505, 'Bob', 56, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7574, 'Alice', 63, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5321, 'Charlie', 46, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (800, 'Alice', 53, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (57, 'Grace', 25, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1447, 'Judy', 35, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7872, 'David', 61, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8623, 'Heidi', 42, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9878, 'Bob', 32, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8254, 'Heidi', 46, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6001, 'Bob', 65, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9589, 'Heidi', 39, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9296, 'Alice', 18, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6323, 'Bob', 56, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6053, 'Frank', 30, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4426, 'David', 38, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3873, 'Alice', 48, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1058, 'Ivan', 25, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7082, 'Frank', 33, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (384, 'Bob', 43, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5497, 'David', 31, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3291, 'Frank', 63, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (9753, 'Heidi', 48, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8490, 'Grace', 34, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6643, 'Frank', 64, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1426, 'David', 28, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7962, 'Charlie', 18, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8973, 'Judy', 34, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9540, 'Alice', 29, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6532, 'Heidi', 53, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6743, 'Ivan', 27, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4965, 'Bob', 62, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (59, 'Ivan', 61, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7030, 'Heidi', 42, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (93, 'Heidi', 41, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7944, 'Alice', 37, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6630, 'Alice', 39, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8442, 'Heidi', 48, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3512, 'Eve', 26, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8376, 'Frank', 25, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1407, 'Judy', 64, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (854, 'David', 58, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6240, 'Charlie', 59, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7923, 'Heidi', 19, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8093, 'Alice', 54, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6301, 'David', 22, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2057, 'Grace', 31, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1456, 'Grace', 44, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5076, 'Heidi', 28, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3594, 'Alice', 45, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5697, 'Bob', 36, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6198, 'Charlie', 32, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7322, 'Alice', 53, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (270, 'David', 30, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5826, 'Charlie', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (775, 'Frank', 27, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1219, 'David', 37, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1019, 'Ivan', 22, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5619, 'Bob', 46, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9854, 'Grace', 21, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9310, 'Ivan', 42, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2485, 'Ivan', 50, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7832, 'Eve', 41, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (146, 'Heidi', 44, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (152, 'Judy', 46, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (9987, 'Bob', 51, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (691, 'Judy', 64, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6694, 'Judy', 44, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7018, 'Grace', 49, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7047, 'Heidi', 42, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6276, 'Eve', 39, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7821, 'Judy', 34, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5192, 'Charlie', 54, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9870, 'Charlie', 33, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9480, 'Heidi', 19, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (898, 'Frank', 64, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2780, 'Heidi', 61, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5214, 'Frank', 56, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6688, 'Grace', 42, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9392, 'Frank', 60, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (819, 'Grace', 53, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8096, 'Heidi', 31, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6442, 'Heidi', 42, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1469, 'Eve', 60, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3268, 'Eve', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6566, 'Alice', 23, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4124, 'Ivan', 50, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2211, 'Ivan', 47, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3413, 'Frank', 49, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3350, 'Eve', 36, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (752, 'Heidi', 33, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3918, 'Judy', 45, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (1775, 'Eve', 63, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (4530, 'Ivan', 61, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1092, 'David', 65, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1709, 'Heidi', 55, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (8227, 'Ivan', 51, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (593, 'Charlie', 33, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (530, 'Ivan', 31, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2995, 'David', 43, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9153, 'Ivan', 52, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5101, 'Bob', 63, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7630, 'Frank', 37, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9555, 'Heidi', 20, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4414, 'David', 27, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7309, 'Charlie', 53, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9107, 'Heidi', 33, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1262, 'Ivan', 30, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6505, 'Frank', 18, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6845, 'Frank', 35, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3506, 'Eve', 48, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (769, 'Frank', 63, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7883, 'Frank', 39, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8183, 'Charlie', 35, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5601, 'Eve', 51, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8251, 'Ivan', 64, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (303, 'Judy', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4172, 'Eve', 43, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7812, 'Judy', 30, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3926, 'Grace', 57, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4014, 'Bob', 45, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7798, 'David', 22, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1762, 'David', 43, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8784, 'Charlie', 62, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3674, 'Bob', 24, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2284, 'Judy', 40, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (958, 'Charlie', 65, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (13, 'Alice', 31, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (9933, 'David', 57, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4817, 'Heidi', 47, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7268, 'Charlie', 29, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8828, 'Charlie', 30, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5530, 'Frank', 31, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1322, 'Heidi', 39, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2630, 'Bob', 61, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8555, 'Heidi', 22, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2660, 'David', 35, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3134, 'Heidi', 62, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5981, 'Eve', 35, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2497, 'Judy', 31, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3419, 'Charlie', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (654, 'Charlie', 22, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8400, 'Frank', 20, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (9593, 'Judy', 48, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1207, 'Ivan', 58, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4550, 'Judy', 60, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8118, 'Charlie', 47, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6380, 'Frank', 28, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6906, 'Bob', 29, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1175, 'Heidi', 50, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5917, 'Ivan', 21, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6909, 'David', 51, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9288, 'David', 36, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2775, 'David', 27, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9837, 'Charlie', 61, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7035, 'Judy', 48, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9356, 'Bob', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6619, 'David', 32, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (8962, 'Eve', 44, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2430, 'Grace', 35, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1823, 'Charlie', 20, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2712, 'Heidi', 42, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4904, 'Heidi', 27, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9105, 'Bob', 21, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (339, 'Grace', 59, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (7274, 'Heidi', 34, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6866, 'Frank', 43, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4563, 'Eve', 48, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4144, 'Ivan', 45, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1753, 'Charlie', 45, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2952, 'Judy', 51, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1187, 'Eve', 19, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4414, 'Grace', 59, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (110, 'Heidi', 32, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3460, 'Alice', 28, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4336, 'Grace', 42, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6543, 'Judy', 56, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1428, 'Frank', 62, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1244, 'Charlie', 58, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (2085, 'Judy', 43, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2712, 'Grace', 49, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4569, 'Eve', 25, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6506, 'Judy', 24, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9450, 'Alice', 64, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5457, 'Ivan', 49, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7156, 'Bob', 34, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (3882, 'Charlie', 62, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5645, 'Bob', 29, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (662, 'David', 24, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2376, 'Bob', 38, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (73, 'Eve', 53, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (3024, 'Ivan', 31, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8260, 'Charlie', 58, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1350, 'Heidi', 40, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (119, 'David', 36, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3360, 'David', 55, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2348, 'Charlie', 59, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (574, 'Judy', 63, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5643, 'Grace', 38, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2364, 'Charlie', 43, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8258, 'Eve', 44, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4468, 'Bob', 56, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2586, 'Ivan', 64, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1481, 'David', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2669, 'Frank', 26, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3839, 'Grace', 45, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7009, 'Charlie', 44, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9478, 'Charlie', 36, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9172, 'Charlie', 37, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3987, 'Alice', 38, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9442, 'Ivan', 56, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7196, 'Alice', 47, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (8411, 'Bob', 60, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (1060, 'Judy', 35, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4907, 'Judy', 50, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (455, 'Grace', 53, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (3142, 'Ivan', 31, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9436, 'Bob', 23, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (1916, 'Ivan', 51, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1815, 'Grace', 38, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4642, 'Eve', 62, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2004, 'Frank', 42, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9259, 'David', 25, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (26, 'Ivan', 65, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1305, 'Frank', 44, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (4518, 'Heidi', 62, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3798, 'Heidi', 55, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7261, 'David', 60, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4007, 'Bob', 21, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7910, 'Charlie', 35, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9722, 'Ivan', 63, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (726, 'Eve', 36, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6594, 'Frank', 48, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (284, 'Alice', 47, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2044, 'Alice', 23, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3972, 'Charlie', 19, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (683, 'Grace', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (907, 'David', 24, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (73, 'Bob', 37, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2079, 'Charlie', 35, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (1144, 'Eve', 64, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (802, 'Eve', 35, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1292, 'Bob', 46, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8942, 'Grace', 20, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (199, 'Bob', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4487, 'Frank', 64, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6946, 'Charlie', 65, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (4967, 'Eve', 22, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6490, 'Alice', 47, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1768, 'Judy', 39, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8045, 'Frank', 58, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (5250, 'Bob', 60, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7922, 'David', 19, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1505, 'Charlie', 63, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (3014, 'Judy', 53, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (202, 'Frank', 21, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2835, 'Bob', 29, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2470, 'Frank', 22, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8293, 'Grace', 53, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7776, 'Charlie', 46, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (7143, 'Bob', 22, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8273, 'Bob', 22, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (7122, 'Charlie', 23, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1977, 'Charlie', 53, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (3003, 'Judy', 42, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (4632, 'Ivan', 41, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9046, 'Alice', 46, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (6632, 'Grace', 61, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8558, 'Bob', 25, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1543, 'Eve', 32, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5936, 'Alice', 32, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4170, 'Frank', 55, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2051, 'Heidi', 60, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (5090, 'Ivan', 41, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3692, 'Eve', 62, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6638, 'Alice', 24, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4547, 'Grace', 20, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6004, 'Alice', 48, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (1850, 'Alice', 57, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9409, 'Frank', 18, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (3314, 'Ivan', 62, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (2790, 'Judy', 22, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (6134, 'Grace', 22, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (3155, 'Charlie', 60, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4577, 'Alice', 31, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9224, 'Eve', 60, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (7293, 'Charlie', 51, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8945, 'Heidi', 28, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5275, 'Heidi', 41, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2094, 'Charlie', 64, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6132, 'Grace', 61, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (88, 'Bob', 33, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8366, 'Frank', 58, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2139, 'Bob', 25, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5593, 'Charlie', 60, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6706, 'Judy', 55, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5596, 'Grace', 44, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9424, 'David', 34, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (3229, 'Heidi', 54, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3617, 'Ivan', 42, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6656, 'Frank', 57, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5622, 'Eve', 54, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (724, 'Ivan', 36, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (6536, 'Alice', 32, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2749, 'Eve', 54, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (9741, 'Eve', 56, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7571, 'Bob', 63, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (9399, 'Charlie', 60, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (5063, 'Frank', 59, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5915, 'Ivan', 48, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (5591, 'Grace', 24, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (5191, 'Judy', 42, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (880, 'Bob', 18, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7282, 'Alice', 45, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4178, 'Bob', 56, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (9839, 'Judy', 27, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (6974, 'Grace', 48, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2310, 'Frank', 30, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (1720, 'Grace', 29, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2605, 'Ivan', 62, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9769, 'Eve', 60, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (4066, 'Grace', 26, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (4149, 'Bob', 42, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (2093, 'Grace', 35, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6494, 'Charlie', 28, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (8664, 'Alice', 29, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6230, 'Charlie', 51, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (1861, 'Grace', 26, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6022, 'Bob', 20, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (2852, 'Grace', 18, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6736, 'Ivan', 62, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (4231, 'Eve', 43, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9207, 'Judy', 36, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7537, 'Frank', 45, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (7854, 'Eve', 59, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5175, 'David', 63, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9441, 'Charlie', 64, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6722, 'Heidi', 57, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6743, 'Judy', 29, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (9810, 'Grace', 32, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (1478, 'Alice', 37, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4027, 'Bob', 31, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (3681, 'Ivan', 34, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1354, 'Alice', 51, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (8228, 'Frank', 24, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (581, 'Judy', 64, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7589, 'Grace', 54, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (7942, 'David', 35, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (8066, 'Eve', 50, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5246, 'Heidi', 43, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7019, 'David', 48, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (3188, 'Heidi', 59, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (2380, 'Heidi', 30, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7114, 'Bob', 58, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2305, 'Alice', 31, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (4870, 'Grace', 33, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (8368, 'Alice', 41, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5065, 'David', 41, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3220, 'Bob', 39, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9291, 'Charlie', 37, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (4198, 'Ivan', 52, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (7131, 'Eve', 31, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6030, 'Judy', 24, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6410, 'Bob', 30, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (6074, 'Charlie', 48, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (2491, 'Ivan', 37, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (4486, 'Frank', 45, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5878, 'Heidi', 38, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7528, 'Heidi', 39, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (1135, 'Eve', 58, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (6437, 'David', 20, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3349, 'Ivan', 27, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2960, 'Frank', 33, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (6135, 'Judy', 42, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (8193, 'Judy', 22, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1303, 'Bob', 35, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (899, 'Charlie', 61, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (8494, 'Judy', 57, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (5592, 'Ivan', 38, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (2936, 'David', 64, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (1423, 'Ivan', 63, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5621, 'David', 31, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6877, 'Frank', 27, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (15, 'David', 33, 'Chicago');
INSERT INTO my_table (id, name, age, city) VALUES (19, 'Bob', 19, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (62, 'Bob', 33, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (7062, 'Charlie', 31, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2007, 'Heidi', 32, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (5134, 'Alice', 59, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3299, 'Charlie', 19, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (3830, 'Ivan', 62, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (2740, 'Eve', 48, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (7177, 'Judy', 48, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (3705, 'David', 27, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3237, 'Judy', 44, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (9784, 'Frank', 59, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (2524, 'Eve', 47, 'San Antonio');
INSERT INTO my_table (id, name, age, city) VALUES (5259, 'Frank', 31, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (9920, 'Heidi', 36, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (6030, 'Eve', 47, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (6563, 'Heidi', 50, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (3755, 'Bob', 21, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (5711, 'David', 62, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1744, 'Judy', 23, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5714, 'David', 29, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (6620, 'David', 45, 'Dallas');
INSERT INTO my_table (id, name, age, city) VALUES (1744, 'Heidi', 60, 'New York');
INSERT INTO my_table (id, name, age, city) VALUES (5460, 'Charlie', 24, 'Los Angeles');
INSERT INTO my_table (id, name, age, city) VALUES (501, 'David', 34, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (9888, 'Heidi', 63, 'San Jose');
INSERT INTO my_table (id, name, age, city) VALUES (2196, 'David', 50, 'Phoenix');
INSERT INTO my_table (id, name, age, city) VALUES (8344, 'Charlie', 61, 'Philadelphia');
INSERT INTO my_table (id, name, age, city) VALUES (9583, 'Alice', 21, 'Houston');
INSERT INTO my_table (id, name, age, city) VALUES (7752, 'Heidi', 23, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (5031, 'Eve', 44, 'San Diego');
INSERT INTO my_table (id, name, age, city) VALUES (1810, 'Alice', 32, 'Chicago');
